# Generated by Django 5.2.8 on 2025-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
